openapi: 3.0.3
info:
  title: InnovatEPAM Portal Blind Review API Contract
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /ideas:
    get:
      summary: List ideas with role-aware identity masking
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Idea list response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IdeaListItem'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /ideas/{id}:
    get:
      summary: Get idea detail with blind-review identity policy
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Idea detail response with context-aware identity fields
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdeaDetail'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /ideas/{id}/status:
    patch:
      summary: Evaluate idea without exposing creator identity details
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StatusUpdateRequest'
      responses:
        '200':
          description: Status updated with blind-review-safe response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusUpdateResponse'
        '400':
          description: Invalid request or transition
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden (non-admin)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Idea not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    IdeaListItem:
      type: object
      required:
        - id
        - title
        - description
        - category
        - status
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        category:
          type: string
        status:
          type: string
        comment:
          type: string
          nullable: true
        createdByUserId:
          type: string
          description: Present only in submitter personal-view context
          nullable: true
    IdeaDetail:
      allOf:
        - $ref: '#/components/schemas/IdeaListItem'
        - type: object
          properties:
            attachment:
              nullable: true
              type: object
              additionalProperties: true
            evaluationHistory:
              type: array
              items:
                $ref: '#/components/schemas/EvaluationHistoryEntry'
    EvaluationHistoryEntry:
      type: object
      required:
        - status
        - reviewerId
        - timestamp
      properties:
        status:
          type: string
        comment:
          type: string
          nullable: true
        reviewerId:
          type: string
        timestamp:
          type: string
          format: date-time
    StatusUpdateRequest:
      type: object
      required:
        - status
      properties:
        status:
          type: string
        comment:
          type: string
          nullable: true
    StatusUpdateResponse:
      type: object
      required:
        - id
        - status
      properties:
        id:
          type: string
        status:
          type: string
        comment:
          type: string
          nullable: true
        historyEntry:
          $ref: '#/components/schemas/EvaluationHistoryEntry'
    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
