openapi: 3.0.3
info:
  title: InnovatEPAM Portal Idea Scoring API Contract
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /ideas/{id}/score:
    patch:
      summary: Create or update idea score (admin only)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScoreRequest'
      responses:
        '200':
          description: Score saved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScoreResponse'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden (non-admin)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Idea not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /ideas/ranked:
    get:
      summary: List ideas sorted by total score
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Ranked idea list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RankedIdea'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ScoreRequest:
      type: object
      required:
        - impact
        - feasibility
        - innovation
      properties:
        impact:
          type: integer
          minimum: 1
          maximum: 5
        feasibility:
          type: integer
          minimum: 1
          maximum: 5
        innovation:
          type: integer
          minimum: 1
          maximum: 5

    ScoreResponse:
      type: object
      required:
        - ideaId
        - impact
        - feasibility
        - innovation
        - totalScore
      properties:
        ideaId:
          type: string
        impact:
          type: integer
        feasibility:
          type: integer
        innovation:
          type: integer
        totalScore:
          type: number
          format: float
        scoredAt:
          type: string
          format: date-time

    RankedIdea:
      type: object
      required:
        - id
        - title
        - status
        - impact
        - feasibility
        - innovation
        - totalScore
        - rank
      properties:
        id:
          type: string
        title:
          type: string
        status:
          type: string
        impact:
          type: integer
        feasibility:
          type: integer
        innovation:
          type: integer
        totalScore:
          type: number
          format: float
        rank:
          type: integer
          minimum: 1

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
